#!/bin/bash

docker exec nginx certbot --nginx -d lefodeurcou.fr -d www.lefodeurcou.fr -m lefodeurcou@gmail.com --agree-tos -w /usr/share/nginx/html/letsencrypt/

crontab -l | { cat; echo "00 04 * * 1 docker exec nginx renew --quiet"; } | crontab -
