#!/bin/bash

source ./lemp.env

run='all'
for arg in "$@"; do
	if [ "$arg" = "mysql" ]
	then
		run='mysql';
	elif [ "$arg" = "php" ]
	then
		run='php';
	elif [ "$arg" = "nginx" ]
	then
		run='nginx';
	fi
done

if [ "$run" = "all" ]
then
	./lemp.bin/d-php $phpVersion
	./lemp.bin/d-mysql $mysqlVersion
	./lemp.bin/d-nginx
elif [ "$run" = "php" ]
then
	./lemp.bin/d-php $phpVersion
elif [ "$run" = "mysql" ]
then
	./lemp.bin/d-mysql $mysqlVersion
elif [ "$run" = "nginx" ]
then
	./lemp.bin/d-nginx
fi